apiVersion: v1
kind: Pod
metadata:
  name: blog-app-pod
spec:
  containers:
  - name: Go App Container
    image: mongo:4.4
    command: ["mongod", "--bind_ip_all"]
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-storage
      mountPath: /data/db
  volumes:
  - name: mongo-storage
    persistentVolumeClaim:
      claimName: aws-pvc



