name: Continuous Deployment

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push App Image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ved104/blog-go-app:${{ github.sha }}

            - name: Clone staging-ops repo, update image tags, and push tags
              env:
                  PAT: ${{ secrets.PAT }}
              run: |

                  git clone https://github.com/BadadheVed/Go-Notification-Argo ops-repo
                  cd ops-repo


                  sed -i 's|image: ved104/blog-go-app:.*|image: ved104/blog-go-app:${{ github.sha }}|' deploymentApp.yml


                  git config user.name "GitHub Actions Bot"
                  git config user.email "actions@github.com"


                  git add .
                  git commit -m "Update server image tags to ${{ github.sha }}"


                  git push https://${{ secrets.PAT }}@github.com/BadadheVed/Go-Notification-Argo.git main
